name: Deploy App

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HOST: ubuntu@13.61.35.91
      DEPLOY_DIRECTORY: /home/ubuntu/apps/url-shortener
      CONFIG_PATH: /home/ubuntu/apps/url-shortener/config/prod.yaml
      ENV_FILE_PATH: /home/ubuntu/apps/url-shortener/config.env

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.tag }}
      - name: Check if tag exists
        run: |
          git fetch --all --tags
          if ! git tag | grep -q "^${{ github.event.inputs.tag }}$"; then
            echo "error: Tag '${{ github.event.inputs.tag }}' not found"
            exit 1
          fi
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.24.0
      - name: Build app
        run: |
          go mod download
          go build -o url-shortener ./cmd/url-shortener
      - name: Deploy to VM
        run: |
          sudo apt-get install -y ssh rsync
          echo "$DEPLOY_SSH_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ${{ env.HOST }} "mkdir -p ${{ env.DEPLOY_DIRECTORY }}"
          rsync -avz -e 'ssh -i deploy_key.pem -o StrictHostKeyChecking=no' --exclude='.git' ./ ${{ env.HOST }}:${{ env.DEPLOY_DIRECTORY }}
        env:
          DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
      - name: Remove old systemd service file
        run: |
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ${{ env.HOST }} "sudo rm -f /etc/systemd/system/url-shortener.service"
      - name: List workspace contents
        run: |
          echo "Listing deployment folder contents:"
          ls -la ${{ github.workspace }}/deployment
      - name: Create environment file on server
        run: |
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ${{ env.HOST }} "\
          echo 'CONFIG_PATH=${{ env.CONFIG_PATH }}' | sudo tee ${{ env.ENV_FILE_PATH }} > /dev/null && \
          echo 'HTTP_SERVER_PASSWORD=${{ secrets.AUTH_PASS }}' | sudo tee -a ${{ env.ENV_FILE_PATH }} > /dev/null && \
          sudo chmod 600 ${{ env.ENV_FILE_PATH }} && \
          sudo chown ubuntu:ubuntu ${{ env.ENV_FILE_PATH }}"
      - name: Upload systemd service file
        run: |
          scp -i deploy_key.pem -o StrictHostKeyChecking=no \
            ${{ github.workspace }}/deployment/url-shortener.service \
            ${{ env.HOST }}:/tmp/url-shortener.service
      - name: Move service file to /etc/systemd/system
        run: |
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ${{ env.HOST }} "\
            sudo mv /tmp/url-shortener.service /etc/systemd/system/url-shortener.service && \
            sudo chown root:root /etc/systemd/system/url-shortener.service && \
            sudo chmod 644 /etc/systemd/system/url-shortener.service"
      - name: Reload and restart service
        run: |
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ${{ env.HOST }} "\
            sudo systemctl daemon-reload && \
            sudo systemctl restart url-shortener.service && \
            sudo systemctl status url-shortener.service"
      - name: Fix permissions of systemd service
        run: |
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ${{ env.HOST }} "sudo chown root:root /etc/systemd/system/url-shortener.service && sudo chmod 644 /etc/systemd/system/url-shortener.service"
      - name: Start application
        run: |
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ${{ env.HOST }} "sudo systemctl daemon-reload && sudo systemctl restart url-shortener.service"